Repository codeaashu/DevDisplay, pull requests merged in 2024-12, with the labels that each got.

#581 add: Pranathi Balabathuni
  public/data/pranathibalabathuni.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#582 Added profile for dpgaharwal
  public/data/dpgaharwal.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#593 Fix: Add my profile details
  public/Pragya1601.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#596 Profile addition
  public/data/shyamenk.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#597 add: Anuj Saha
  public/data/AnujSaha0111.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#608 Added more profile links - Instagram and Email
  README.md
  src/components/Profile/Profile.jsx
  src/components/ProfileSkeleton/ProfileSkeleton.jsx
Labels: DevDisplay, Dev Enhancer, Dev Innovator

#609 Update Ashutosh singh Json data
  public/data/codeaashu.json
Labels: DevDisplay, Dev Enhancer, Dev Innovator

#610 Create akhileshverma92.json
  public/data/akhileshverma92.json
Labels: DevDisplay, Dev Pioneer

#612 Gaurav Karakoti
  public/data/GauravKarakoti.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#616 add: Syed salma
  public/data/salmasyed19.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#613 Srujan G S
  public/data/srujanGowda08.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#615 add: Tarun Kumar
  public/data/tarunkumar2005.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#614 add: NOOB-3301
  public/data/NOOB-3301.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#618 add : Patel Dhruv Rakeshkumar
  public/data/dhrupatel031205.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC

#619 Sahil Sharma
  public/data/Sahil-Bhardwaj29.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC

#620 "Add Prashast Nigam's profile"
  public/data/Prashast4438.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC

#621 Update profile json
  public/Shashikumar-ezhilarasu.json
Labels: DevDisplay, Dev Pioneer, SWOC

#622 add: salma syed
  public/data/salmasyed1909.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC

#623 Create Sanskriti65.json
  public/data/Sanskriti65.json
Labels: DevDisplay, Dev Pioneer, SWOC

#624 Himanshu Sharma
  public/data/himanshu7437.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC

#625 add: Sachin Pathak
  public/data/sachinpathak123.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC

#626 add: Megh Deb
  public/data/Megh2005.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC

#628 add : falak vhora
  public/data/falak412.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC

#629 add : Sudhanshu Saini
  public/data/Sudhanshu248.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#630 Harleen Kaur Bhullar
  public/data/HarleenKaurBhullar.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#631 Himanshu Kumar
  public/data/Himanshu-kumar025.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#632 Added PrathamDwivedi27
  public/data/PrathamDwivedi27.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#633 [ADD] New profile - Azfar Alam
  public/data/azfaralam.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#634 Adding Profile Hitesh
  public/data/Hitesh.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#635 add: Rupesh Varshney
  public/data/rupeshv2121.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#636 add GyanaPrakashSahoo
  public/data/GyanaPrakashSahoo7853.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#637 Create HarshVaidya.json
  public/data/HarshVaidya.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#638 add: ThePhoenix08
  public/data/ThePhoenix08.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#639 add: Daksh Jain
  public/data/Dash10107.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#661 [Bug]: greetings.yml is not correctly configured #661
  .github/workflows/greetings.yml
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#640 add: Ajay Kumar Teli
  public/iAmAjayTeli.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#662 add: Abhishek Kumar
  public/data/ctrlabhi.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#659 T Mohamed Yaser
  public/data/Yaser-123.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#658 add: Harsh Mishra
  public/data/harsh02mishra.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#657 Update shubhcoding01.json
  public/data/shubhcoding01.json
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#656 add: Namratha Rao
  public/data/Nam-17.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#655 add: Gaddam Meghana
  Gaddam-megha.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#654 add : Subrata Das
  public/data/subratadasGit.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#653 Add: Sudipto Biswas
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#652 Navneet1206
  public/data/Navneet1206.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#651 add: Arnav Agarwal
  public/data/Arnav-Agarwal-01.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#650 add : SHAH ROCHAN VIMALBHAI
  public/data/rochanshah15.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#649 add: 712Kunal
  public/data/712Kunal.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#648 add Pratik Ghuge
  public/data/Frpratik.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#644 add: Vinita More
  public/data/vimore03.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#674 add: Sumit Kumar
  public/data/sumo47.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#672 add: V Pratheek (Project Admin and Project Mentor at SWOC '25)
  public/data/pratheekv39.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#671 add: Smriti Eligar
  public/data/Smriti-ELigar.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#670 add: Gurram Deekshitha Reddy
  public/data/gurramdikshareddy.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#666 Bug]: greetings.yml is not correctly configured #660
  .github/workflows/greetings.yml
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#646 add: Avni Singh
  public/data/avnisinngh.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#676 Add : Nikhil Bhange
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#678 add: Kumari Shubhangini
  public/data/Shuxxsgini.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#679 add: Subham Mani
  public/data/iSubhamMani.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#680 Add: Nikhil Bhange
  public/data/nikhilbhange96.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#682 Add : Mann Prajapati
  public/data/mann-prajapati05.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#684 Ankit Shaw
  public/data/AnkitShaw-100.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#685 shreya shaw
  public/data/shreyashaw05.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#683 Added my profile in public folder
  public/data/Dev-Dhruba2.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#687 Add : Ayush Prajapati
  public/data/Ayush-pra.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#686 Kanishka Tyagi
  public/data/sachiikrish.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#688 Kanishka Tyagi
  public/data/sachiikrish.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25
