Repository codeaashu/DevDisplay, pull requests merged in 2024-11, with the labels that each got.

#511 Ayush Koundel
  public/data/lazzysimp.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#520 Krish Gupta
  public/data/KRISHkg31.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#517 added:: Meta Tags, robots.txt, sitemaps for SEO Enhancement
  generate-sitemap.js
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap.xml
  src/App.js
Labels: enhancement, hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level2

#516 Create SECURITY.md
  SECURITY.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level2

#521 add: adrishti
  public/data/drishtii.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#522 Feat/add profile
  public/data/Abhi0049k.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#528 Added my profile : Akash Jana
  public/data/AkashJana18.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#531 add: Dorian Niemiec
  public/data/DorianNiemiecSVRJS.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#537 add: Mehfooj Alam
  public/data/Savvythelegend.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#534 Created codernotme
  public/data/codernotme.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#533 Saurabh kumar
  public/data/Saurabh kumar
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#538 add: Ujjwal Gupta
  public/data/ujjwalgupta2021.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#545 add: Pranay Deep Korada
  public/data/pranaydeep1.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#546 add: Dinesh Kottakota
  public/data/dineshkottaKota.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#547 Home Page added
  package-lock.json
  package.json
  src/App.css
  src/Page/TechDisplay.jsx
  src/components/Globe.jsx
  src/components/Navbar.jsx
Labels: enhancement, hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#550 add: Akshay Kumar
  public/data/akshay0611.json
  src/ProfilesList.json
Labels: opensource, ieee-igdtuw, DevDisplay, Dev Pioneer

#551 add: Saumya Yadav
  public/data/saumyayadav25.json
  src/ProfilesList.json
Labels: opensource, ieee-igdtuw, DevDisplay, Dev Pioneer

#555 add: Sai Smruti Ranjan Das
  public/data/saismrutiranjan18.json
  src/ProfilesList.json
Labels: ieee-igdtuw, DevDisplay, Dev Pioneer

#552 add: Shreya Nigam
  public/data/itsshreyanigam.json
  src/ProfilesList.json
Labels: ieee-igdtuw, DevDisplay, Dev Pioneer

#557 add: Riddhi Rustagi
  public/data/Riddhi050803.json
  src/ProfilesList.json
Labels: ieee-igdtuw, DevDisplay, Dev Pioneer

#562 AvniSharma.json added
  public/data/AvniSharma.json
  src/ProfilesList.json
Labels: ieee-igdtuw, DevDisplay, Dev Pioneer

#548 Globe Size Overallping in Mobile Fixed
  public/assets/SupportedBy/GitBookLight_1.png
  src/Page/Home.jsx
  src/Page/TechDisplay.jsx
  src/components/Globe.jsx
  src/index.css
Labels: enhancement, DevDisplay, Dev Enhancer, Dev Innovator

#565 add: Chandrika Sruthi
  public/data/chinna3206.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#564 Create deepeshmlgupta.json
  public/data/deepeshmlgupta.json
Labels: DevDisplay, Dev Pioneer

#567 add: Sampada Tiwari
  public/data/sampadatiwari30.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#569 add: Adwitya Chakraborty
  public/data/adwityac.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#568 add : Bhuva Bhavik
  public/data/bhuvabhavik.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer
