Repository codeaashu/DevDisplay, pull requests merged in 2024-10, with the labels that each got.

#102 Fix bug (Theme Mode Does Not Follow Device Default Setting)
  src/components/Sidebar/Sidebar.jsx
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024

#119 Chirag Khairnar
  public/data/LegendCK.json
  src/ProfilesList.json
Labels: good first issue, hacktoberfest, hacktoberfest2024, gssoc24, opensource

#120 bug fixed and update previous files
  src/App.js
  src/Homepage.jsx
  src/Page/Opportunities.jsx
  src/components/Search/Search.jsx
  src/components/Sidebar/Sidebar.jsx
Labels: enhancement, hacktoberfest, hacktoberfest2024, gssoc24, opensource

#113 add: Vighnesh Mandavkar
  public/data/infernodragon456.json
  src/ProfilesList.json
Labels: enhancement, hacktoberfest, hacktoberfest2024, gssoc24, opensource

#121 Add: Gajendra Kumar
  public/data/MrGajendra.json
  src/ProfilesList.json
Labels: good first issue, hacktoberfest, hacktoberfest2024, gssoc24, opensource

#122 update opportunites
  package-lock.json
  package.json
  src/Page/Opportunities.jsx
Labels: enhancement, hacktoberfest, hacktoberfest2024, gssoc24, opensource

#123 update opportunities
  package-lock.json
  package.json
  src/Page/Opportunities.jsx
Labels: bug, enhancement, hacktoberfest, hacktoberfest2024, gssoc24, opensource

#114 add : Vaibhav Kulkarni
  public/data/ivaibhavkulkarni.json
  src/ProfilesList.json
Labels: good first issue, hacktoberfest, hacktoberfest2024, gssoc24, opensource

#124 add: Cormac Packer
  public/data/Cormwww.json
  src/ProfilesList.json
Labels: good first issue, hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted

#133 add: Sagar2006
  public/data/Sagar2006.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted

#125 Adding my profile
  public/data/oken.json
  src/ProfilesList.json
Labels: good first issue, hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted

#141 changing some files
  Welcome To DevDisplay/Welcome To DevDisplay - Oken Keithellakpam.png
  Welcome To DevDisplay/Welcome To DevDisplay - Vaibhav Kulkarni.png
  Welcome To DevDisplay/Welcome To DevDisplay - Vighnesh Mandavkar.png
  public/data/Cormwww.json
  public/data/Sagar2006.json
  public/data/ivaibhavkulkarni.json
  public/data/oken.json
  public/index.html
  src/ProfilesList.json
  src/components/Search/Search.jsx
Labels: bug, enhancement, gssoc24, hacktoberfest-accepted

#147 add: varunkasyap
  public/data/varunkasyap.json
  src/ProfilesList.json
Labels: good first issue, hacktoberfest, hacktoberfest2024, gssoc24, hacktoberfest-accepted

#146 add : Unnimaya K
  public/data/Unnimaya6122004.json
  src/ProfilesList.json
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext

#148 ADD: Ganesh Kumar
  public/data/codewithganeshhh.json
  src/ProfilesList.json
Labels: hacktoberfest, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext

#149 Add: Sharad Chandra Reddy
  public/data/SCR01.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext

#151 chore(fix): pagination render
  src/Homepage.jsx
Labels: bug, hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext

#153 Create elic4vet.json
  public/data/elic4vet.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext

#156 add: munnavuyyuru
  public/data/munnavuyyuru.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, hacktoberfest-accepted, gssoc-ext

#159 add: Dhruv Jain
  package-lock.json
  public/data/dhruvjain23.json
  src/ProfilesList.json
Labels: enhancement, hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext

#164 Add: Sohel Sheikh
  public/data/iamsohelx.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext

#165 add: Sai Dinesh
  public/data/saidinesh49.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext

#166 Fixed buttons
  src/components/Sidebar/Sidebar.jsx
Labels: enhancement, hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext

#188 Added Profile Data
  public/data/ishap11.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext

#191 Added Ayush Pandey
  public/data/Ayush.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext

#198 adding twitter and other links
  public/data/mrpeace07.json
Labels: enhancement, hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#203 Hayley Lemon
  public/haylemon.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#204 add: Tyarla Shirisha
  public/data/Shirisha-16.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#210 add: minji105
  public/data/minji105.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#213 added my profile as per the instructions of #111 issue
  public/data/harshendram.json
  src/ProfilesList.json
Labels: good first issue, hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#221 add : Haseeb Zaki
  public/data/haseebzaki-07.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#226 add: created my profile as per the instructions of #111 issue
  public/data/coderKrysio.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#225 add: Chandrima Hazra
  public/data/hazraChandrima.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#220 Vastavikadi _patch-1
  public/data/vastavikadi.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#219 add: Rohith K
  public/data/RohithNair27.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#234 add:Himanshu Pandey
  public/data/himanshupandey21.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#235 add AjayAchugatla
  public/data/AjayAchugatla.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#241 added my profile as per the instructions
  public/data/IkkiOcean.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#244 Added profile
  public/data/Brijeshthummar02.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#246 Profile add
  public/data/Aditijainnn.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#247 Add : Anusha Burnwal
  public/data/Anushaburnwal.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#249 added : Meet Thakur
  public/data/MeetThakur.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#271 add: Shubham Pandey
  public/data/heizshubham.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#277 add profile: Aditya Bavadekar
  public/data/AdityaBavadekar.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#280 Add Shrutakeerti Datta
  public/data/Shrutakeerti.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#281 add: Gaurav Bomble
  public/data/Gauravtb2253.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#284 Aksh Jaiswal
  public/data/akshjswl.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#294 Prem Kolte
  public/data/Premkolte.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#295 add: Dhruv Agrawal
  public/data/Dhruv80576.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#320 Sameer Khan
  public/data/LazyCodwr.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#326 added my profile
  public/data/Ayush_Gautam.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, hacktoberfest-accepted, gssoc-ext, level1

#329 Added My Profile : HetuKariya
  public/data/HetuKariya.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, hacktoberfest-accepted, gssoc-ext, level1

#331 add: Deepesh Patil
  public/data/deepesh611.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, hacktoberfest-accepted, gssoc-ext, level1

#334 add: Khushi Gupta
  public/data/khushiii-6510.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#335 add: Krishna Kumar
  public/data/0xkrishu.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#337 Paras Verma
  public/data/paras-verma7454.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#338 Added My DevDisplay Profile
  public/data/suryapratapsinghsuryavanshi.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#341 add: Prem Rathod
  public/data/PRathod27.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#343 i have added my profile
  public/data/priyachau12.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#344 Ravi Prakash Pal
  public/data/RaviP9973.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#346 add : Vinay Anand Lodhi
  public/data/VinayLodhi1712.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#345 add: Aryan Barde
  public/data/aryanbarde80.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#349 add: 22Rupesh
  public/data/22Rupesh.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#351 add:Divya N
  public/data/DivyaN10.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#352 shashank cheere
  public/data/shashankch2003.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#354 Addin my profile
  public/data/adi271001.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#356 add: Aditya Singh
  public/data/Axestein.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#357 Arvinder Singh Dhoul
  public/data/arvinder004.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#362 Add : darshini
  public/data/darshini.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#367 add: Deep Raj
  public/data/dhruvsinha3130.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#370 add: Rishitha Nandanapu
  public/data/n14rishitha.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#371 add: Anjali Raikwar
  public/data/ANJI1026.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#373 add: Rupali R
  public/data/Rupali1104.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#375 add: AryanMittal11
  public/data/AryanMittal11.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#376 Added Pushpa472
  public/data/Pushpa472.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#381 add: Divanshi Goyal
  public/data/divanshiii09.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#417 ADDED MY PROFILE (amiya-cyber)
  public/data/amiya-cyber.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#421 Added My Profile to the Data
  public/data/Sambashivarao-Boyina.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#414 The Search Feature of Skills cirteria implement from one skill to mutliple Skills
  src/Homepage.jsx
  src/components/Search/Search.jsx
  src/components/Search/SearchSkill.jsx
  src/components/Search/SearchSkillsContainer.jsx
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level2

#423 Added my profile
  public/data/Dcoder10M.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#425 add: Shantanu Tiwari
  public/data/Shantanu-Tiwari.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#426 AnjanaS
  public/AnjanaS2004.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#436 add: Harsha Rashmi
  public/data/Harsha-01-cmd.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#434 Add: Krish Koria
  public/data/KrishKoria.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#437 add: Harsha Rashmi
  public/data/Coder-Harsha-2805.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#440 add: Shivanjali Karande
  public/data/shivanjalikarande.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#446 add: MAYUR AJIT SAHARE
  public/sahare-mayur-0071.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#447 added details
  public/data/Aditya-PS-05.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, level1

#448 Add: Snehshish Dutta
  public/data/Snehshishdutta.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#459 added chatbot for enhanced user experience
  public/index.html
  src/components/Chatbot.jsx
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#458 Added the Voice search functionality
  public/data/Sambashivarao-Boyina.json
  src/components/Search/Search.jsx
  src/components/Search/VoiceSearch.jsx
Labels: enhancement, hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level3

#461 add: Gokul-MK
  public/data/Gokul-MK.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#462 add: ADURI TEJA
  public/data/ADURITEJA.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#469 Add: TeekshaHarish
  public/data/TeekshaHarish.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#470 add: Bhumika Sharma
  public/data/Bhum-ika.json
  public/data/Gokul-MK.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#465 Bug Fix Gssoc20224 correct to GSSoC'2024
  README.md
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#452 add: khaulanauman
  public/data/khaulanauman.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#473 Done The Enhancements
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level2

#491 Updated skill list AkashDas.json
  public/data/AkashDas.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#497 Added my profile SrishtiChamoli
  public/data/SrishtiChamoli.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#499 Added Eseponiv profile
  public/data/espeoniv.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#501 add: RAVIBABU BOMMANAPALLI
  public/data/Ravibabu910 .json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#507 SATYAM SINGH
  public/data/SATYAM0LUFFY.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#505 Aditya Dhawan
  public/data/adityadhawan44.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1

#508 Add: Achintya Srivastava
  public/data/achintyasrivastav.json
  src/ProfilesList.json
Labels: hacktoberfest, hacktoberfest2024, gssoc24, opensource, hacktoberfest-accepted, gssoc-ext, level1
