Repository codeaashu/DevDisplay, pull requests merged in 2025-01, with the labels that each got.

#695 completed: Tech Resources Page
  public/data/Sahil-Bhardwaj29.json
  src/App.js
  src/Page/PortfolioIdeas.jsx
  src/Page/Resources.jsx
  src/Resouces_Pages/Documentation.jsx
  src/Resouces_Pages/ProgrammingLanguages.jsx
  src/Resouces_Pages/TechNotes.jsx
  src/Resouces_Pages/commonComponents/Footer.jsx
  src/Resouces_Pages/commonComponents/Navbar.jsx
Labels: DevDisplay, Dev Enhancer, Dev Innovator, SWOC, swoc25

#697 add: Abhay Gupta
  public/data/Abhay-hack.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#696 Add Nishant Rana
  public/data/nishantrana07.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#691 add: Shahbaz
  public/data/Shahbaz615.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#690 add: Muhammad Ammaar Quadri
  public/data/ammaarquadri.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#689 add: Darshan G K
  imDarshanGK.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#699 add : Kashika Gupta
  kashikaga.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#705 add: Rohan Shrivastava
  public/data/RohanShrivastava08.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#712 Contribute Page Completed
  public/DevSpring.png
  src/App.js
  src/Page/Contribute.jsx
Labels: DevDisplay, Dev Enhancer, Dev Innovator, SWOC, swoc25

#719 Remaining Pages Completed.
  README.md
  src/App.js
  src/Page/Resources.jsx
  src/Resouces_Pages/AITools.jsx
  src/Resouces_Pages/ContributionsGuide.jsx
  src/Resouces_Pages/InterviewPrep.jsx
  src/Resouces_Pages/OpenSource.jsx
  src/Resouces_Pages/RoadmapGuide.jsx
  src/Resouces_Pages/TopGithubRepo.jsx
Labels: DevDisplay, Dev Enhancer, Dev Innovator, SWOC, swoc25

#727 Projects Section added
  src/App.css
  src/DB/projects.json
  src/Page/ProjectShowcase.jsx
Labels: DevDisplay, Dev Enhancer, Dev Innovator, SWOC, swoc25

#731 update
  public/data/anu098jaiswal.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#730 Add devdisplay12
  public/data/devdisplay12.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#729 Add ubaman34
  public/data/ubaman34.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#728 add:Jeelani
  public/data/Jeelani472.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#723 add : Akash Babu Kushwah
  public/data/akashk6697.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#722 add pankaj
  public/data/Pankajraja01.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#720 add: Kunal Kumar
  public/data/developerkunalonline.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#717 Abuzar Firoz - Profile Added!
  public/data/abuzar.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#715 Create ThunderShadows.json
  public/data/ThunderShadows.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#708 update-details
  public/data/aayishajalal.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#736 add sri harshitha
  public/data/sriharshitha37.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#740 add: RevanthKumarJ
  public/data/revanthkumarJ.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#764 Add jUsTtulika
  public/data/jUsTtulika.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#763 Add ChaitraTM
  public/data/ChaitraTM.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#762 add su-jin1425
  public/data/su-jin1425.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#760 Add mansiruhil
  public/data/mansiruhil
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#759 Md Zeeshan
  public/data/mdz337426.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#758 ADD MD-IRFAN-RAJ profile
  public/data/MD-IRFAN-RAJ.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#756 add Sachintha Nadeeshan
  public/data/Sachin-NK.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#765 Add Ritanshusharma2
  public/data/Ritanshusharma2.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#755 Add MohammedArif9092
  public/data/MohammedArif9092.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#754 Add syamsundaryadla
  public/data/syamsundaryadla.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#753 Add Soumyadipgithub
  public/data/Soumyadipgithub.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#751 FallBack Icon if avatar link not valid and Mail Issue in profile
  src/components/Profile/Profile.jsx
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#750 Add TheChaoticor
  public/data/TheChaoticor.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#749 Requesting to add my profile to DevDisplay
  public/data/SaiBhaskar05.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#747 Add geetanshu7052
  public/data/geetanshu7052.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#746 Add abishekak18
  public/data/abishekak18.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#743 add profile: Suvasis Patra
  public/data/suvasis-patra.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#742 Add KaleidoNexTechnologies
  public/data/KaleidonexTechnologies
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#738 Add gaganjha1
  public/data/gaganjha1.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#745 add : Pavananjali
  package-lock.json
  package.json
  public/data/PavananjaliPamidi.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#774 add: Yaddalapalli-Charan-Kumar-Naidu
  public/data/Charan.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#770 Add Divya-M2004
  public/data/Divya-M2004.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#794 Add shrashti-19
  public/data/shrashti-19.json
  shrashti-19.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#793 Kushal Katare
  public/data/kushal961.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#792 Please add Snig10dha
  public/data/Snig10dha.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#790 add: Akash Rai
  public/data/AKASH722.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#789 add : Shuvadeep Mondal
  public/data/shuvadeepmondal.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#788 add: Akshat Mehrotra
  public/data/Rana-Akshat.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#787 add : Rohith Juluru
  public/data/rohith2201.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#786 Add PHarnoor
  public/data/PHarnoor.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#785 Add Himanshi-code-rgb
  public/data/Himanshi-code-rgb.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#783 Create Coderisa.json
  public/data/Coderisa.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#777 Add pahimauchil
  public/data/pahimauchil.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#775 Add my profile
  public/data/Aparna-cod.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#797 add aadyaasoni
  public/data/aadyaasoni.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#768 Footer enhancement : Solved Issue #767
  package-lock.json
  package.json
  src/Page/DevSpring.jsx
  src/Page/Home.jsx
  src/components/Footer/Footer.jsx
Labels: DevDisplay, Dev Enhancer, Dev Innovator, SWOC, swoc25

#776 404 Not Found Page
  src/App.js
  src/Page/PageNotFound.jsx
Labels: Dev Enhancer, Dev Innovator, SWOC, swoc25

#803 Footer Component Updated
  src/Page/About.jsx
  src/Page/PortfolioIdeas.jsx
  src/Page/ProjectShowcase.jsx
  src/Page/Resources.jsx
  src/Resouces_Pages/AITools.jsx
  src/Resouces_Pages/ContributionsGuide.jsx
  src/Resouces_Pages/Documentation.jsx
  src/Resouces_Pages/InterviewPrep.jsx
  src/Resouces_Pages/OpenSource.jsx
  src/Resouces_Pages/ProgrammingLanguages.jsx
  src/Resouces_Pages/RoadmapGuide.jsx
  src/Resouces_Pages/TechNotes.jsx
  src/Resouces_Pages/TopGithubRepo.jsx
  src/Resouces_Pages/commonComponents/Footer.jsx
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#805 Added Links to Logo and Star the repo
  src/Page/Home.jsx
  src/components/Navbar.jsx
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#804 changed the UI for unimplemented features
  src/Page/Discussions.jsx
  src/Page/IdeaSubmission.jsx
  src/Page/Opportunities.jsx
  src/Page/PortfolioBuilder.jsx
  src/Page/ResumeBuilder.jsx
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#802 Add MukundSwaroop
  public/data/MukundSwaroop.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25
