Repository codeaashu/DevDisplay, pull requests merged in 2025-02, with the labels that each got.

#813 AITools.jsx
  src/Resouces_Pages/AITools.jsx
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#809 individual Journey Page
  src/App.js
  src/components/AchievementJourney/IndividualJourney.js
Labels: DevDisplay, Dev Enhancer, Dev Innovator, SWOC, swoc25

#808 added sponsors Page
  src/App.js
  src/Page/Home.jsx
  src/Page/Sponsor.jsx
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#824 added liveDemo to card
  src/DB/projects.json
  src/Page/ProjectShowcase.jsx
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#822 Update package.json
  package.json
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#823 Update package-lock.json
  package-lock.json
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#819 Create IndustryTrends.jsx
  src/Page/IndustryTrends.jsx
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#818 journey page completed
  src/App.js
  src/Page/JourneyPage.jsx
  src/components/AchievementJourney/IndividualJourney.js
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#814 add : Piyush Gupta
  public/data/Piyush-t24.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#826 fix : globe responsive issue
  src/Page/Home.jsx
  src/components/Globe.jsx
  tailwind.config.js
Labels: DevDisplay, Dev Enhancer, SWOC, swoc25

#828 Add pranati2507
  public/data/pranati2507.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#836 Added E-mail in Dev-Display
  public/data/Brijeshthummar02.json
Labels: DevDisplay, Dev Pioneer, Dev Enhancer

#834 add Rehan
  public/data/rehan.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#832 add ramesh
  public/data/rameshb.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer

#838 add Vaibhav M N
  public/data/Vaibhav2154.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, SWOC, swoc25

#839 Ai career recommendation
  src/App.js
  src/Page/AiCareer.jsx
  src/Page/Home.jsx
  src/api/skillAnalyzer.js
Labels: DevDisplay, Dev Innovator, SWOC, swoc25
