Repository codeaashu/DevDisplay, pull requests merged in 2025-08, with the labels that each got.

#1043 Add SudoAnirudh profile data
  public/data/SudoAnirudh.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, GSSoC, GSSoC'25

#1046 Added my profile JSON and updated ProfilesList
  public/data/Bipasha1005.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, GSSoC, GSSoC'25

#1060 feat: add Nikunj Mehta profile JSON and update ProfilesList.json
  public/data/NikunjMehta.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, GSSoC, GSSoC'25

#1064 add: Parth Patel
  public/data/parth-patel010.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, GSSoC, GSSoC'25

#1070 Added omkumar.json profile
  public/data/omku415.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, GSSoC, GSSoC'25

#1069 Add : Aman Verma
  public/data/hecker8055.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, GSSoC, GSSoC'25

#1086 Divya Jain
  public/data/DivyaJain-DataAnalyst.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, GSSoC, GSSoC'25, Level 1 - GSSoC '25

#1095 Documentation: Updated Readme.md file for GSSoC'25 compliance
  README.md
  public/gssoc logo.png
Labels: DevDisplay, Dev Enhancer, GSSoC, GSSoC'25, Level 2 - GSSoC '25

#1106 Profile added to devdisplay
  backend/package-lock.json
  package-lock.json
  package.json
  public/data/AarushJain.json
  src/Page/JourneyPage.jsx
  src/components/AchievementJourney/IndividualJourney.js
Labels: DevDisplay, Dev Pioneer, Dev Enhancer, GSSoC, GSSoC'25, Level 2 - GSSoC '25

#1088 Add my profile (Rupali2507)
  public/data/Rupali2507.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, GSSoC, GSSoC'25, Level 1 - GSSoC '25

#1087 sakshi bhati
  public/data/sakshi142004.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, GSSoC, GSSoC'25, Level 1 - GSSoC '25

#1111 Fix: Resume PDF export alignment and spacing issues (#1082)
  package-lock.json
  src/components/ResumeBuilder/utils/pdfGenerator.js
Labels: DevDisplay, Dev Enhancer, GSSoC, GSSoC'25, Level 2 - GSSoC '25

#1122 Gupta-02
  public/data/Gupta-02.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer, GSSoC, GSSoC'25, Level 1 - GSSoC '25

#1132 add Vanshikaaa49
  public/data/Vanshikaaa49.json
  src/ProfilesList.json
Labels: DevDisplay, Dev Pioneer
